// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: header.proto

package com.remcarpediem.feignprotobuf.proto.dto;

public final class Header {
  private Header() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_remcarpediem_feignprotobuf_proto_dto_HeaderReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_remcarpediem_feignprotobuf_proto_dto_HeaderReply_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_remcarpediem_feignprotobuf_proto_dto_LineReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_remcarpediem_feignprotobuf_proto_dto_LineReply_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_remcarpediem_feignprotobuf_proto_dto_DistributionReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_remcarpediem_feignprotobuf_proto_dto_DistributionReply_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_remcarpediem_feignprotobuf_proto_dto_TestReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_remcarpediem_feignprotobuf_proto_dto_TestReply_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014header.proto\022(com.remcarpediem.feignpr" +
      "otobuf.proto.dto\032\037google/protobuf/timest" +
      "amp.proto\"\207\003\n\013HeaderReply\022C\n\006field1\030\001 \003(" +
      "\01323.com.remcarpediem.feignprotobuf.proto" +
      ".dto.LineReply\022\016\n\006field2\030\002 \001(\005\022*\n\006field3" +
      "\030\003 \001(\0132\032.google.protobuf.Timestamp\022\016\n\006fi" +
      "eld4\030\004 \001(\t\022\016\n\006field5\030\005 \001(\005\022\016\n\006field6\030\006 \001" +
      "(\t\022\016\n\006field7\030\007 \001(\005\022\016\n\006field8\030\010 \001(\t\022\016\n\006fi" +
      "eld9\030\t \001(\005\022\017\n\007field10\030\n \001(\t\022\017\n\007field11\030\013" +
      " \001(\005\022\017\n\007field12\030\014 \001(\t\022\017\n\007field13\030\r \001(\005\022\017" +
      "\n\007field14\030\016 \001(\t\022\017\n\007field15\030\017 \001(\005\022\017\n\007fiel" +
      "d16\030\020 \001(\t\022\017\n\007field17\030\021 \001(\005\022\017\n\007field18\030\022 " +
      "\001(\t\"\215\003\n\tLineReply\022K\n\006field1\030\001 \003(\0132;.com." +
      "remcarpediem.feignprotobuf.proto.dto.Dis" +
      "tributionReply\022\016\n\006field2\030\002 \001(\005\022*\n\006field3" +
      "\030\003 \001(\0132\032.google.protobuf.Timestamp\022\016\n\006fi" +
      "eld4\030\004 \001(\t\022\016\n\006field5\030\005 \001(\005\022\016\n\006field6\030\006 \001" +
      "(\t\022\016\n\006field7\030\007 \001(\005\022\016\n\006field8\030\010 \001(\t\022\016\n\006fi" +
      "eld9\030\t \001(\005\022\017\n\007field10\030\n \001(\t\022\017\n\007field11\030\013" +
      " \001(\005\022\017\n\007field12\030\014 \001(\t\022\017\n\007field13\030\r \001(\005\022\017" +
      "\n\007field14\030\016 \001(\t\022\017\n\007field15\030\017 \001(\005\022\017\n\007fiel" +
      "d16\030\020 \001(\t\022\017\n\007field17\030\021 \001(\005\022\017\n\007field18\030\022 " +
      "\001(\t\"\330\002\n\021DistributionReply\022\016\n\006field1\030\001 \001(" +
      "\t\022\016\n\006field2\030\002 \001(\005\022*\n\006field3\030\003 \001(\0132\032.goog" +
      "le.protobuf.Timestamp\022\016\n\006field4\030\004 \001(\t\022\016\n" +
      "\006field5\030\005 \001(\005\022\016\n\006field6\030\006 \001(\t\022\016\n\006field7\030" +
      "\007 \001(\005\022\016\n\006field8\030\010 \001(\t\022\016\n\006field9\030\t \001(\005\022\017\n" +
      "\007field10\030\n \001(\t\022\017\n\007field11\030\013 \001(\005\022\017\n\007field" +
      "12\030\014 \001(\t\022\017\n\007field13\030\r \001(\005\022\017\n\007field14\030\016 \001" +
      "(\t\022\017\n\007field15\030\017 \001(\005\022\017\n\007field16\030\020 \001(\t\022\017\n\007" +
      "field17\030\021 \001(\005\022\017\n\007field18\030\022 \001(\t\"\234\001\n\tTestR" +
      "eply\022E\n\006field1\030\001 \001(\01325.com.remcarpediem." +
      "feignprotobuf.proto.dto.HeaderReply\022\016\n\006f" +
      "ield2\030\002 \001(\005\022*\n\006field3\030\003 \001(\0132\032.google.pro" +
      "tobuf.Timestamp\022\014\n\004name\030\004 \001(\tB,\n(com.rem" +
      "carpediem.feignprotobuf.proto.dtoP\001b\006pro" +
      "to3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.TimestampProto.getDescriptor(),
        });
    internal_static_com_remcarpediem_feignprotobuf_proto_dto_HeaderReply_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_remcarpediem_feignprotobuf_proto_dto_HeaderReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_remcarpediem_feignprotobuf_proto_dto_HeaderReply_descriptor,
        new java.lang.String[] { "Field1", "Field2", "Field3", "Field4", "Field5", "Field6", "Field7", "Field8", "Field9", "Field10", "Field11", "Field12", "Field13", "Field14", "Field15", "Field16", "Field17", "Field18", });
    internal_static_com_remcarpediem_feignprotobuf_proto_dto_LineReply_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_remcarpediem_feignprotobuf_proto_dto_LineReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_remcarpediem_feignprotobuf_proto_dto_LineReply_descriptor,
        new java.lang.String[] { "Field1", "Field2", "Field3", "Field4", "Field5", "Field6", "Field7", "Field8", "Field9", "Field10", "Field11", "Field12", "Field13", "Field14", "Field15", "Field16", "Field17", "Field18", });
    internal_static_com_remcarpediem_feignprotobuf_proto_dto_DistributionReply_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_remcarpediem_feignprotobuf_proto_dto_DistributionReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_remcarpediem_feignprotobuf_proto_dto_DistributionReply_descriptor,
        new java.lang.String[] { "Field1", "Field2", "Field3", "Field4", "Field5", "Field6", "Field7", "Field8", "Field9", "Field10", "Field11", "Field12", "Field13", "Field14", "Field15", "Field16", "Field17", "Field18", });
    internal_static_com_remcarpediem_feignprotobuf_proto_dto_TestReply_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_com_remcarpediem_feignprotobuf_proto_dto_TestReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_remcarpediem_feignprotobuf_proto_dto_TestReply_descriptor,
        new java.lang.String[] { "Field1", "Field2", "Field3", "Name", });
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
