// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: header.proto

package com.remcarpediem.feignprotobuf.proto.dto;

/**
 * Protobuf type {@code LineReply}
 */
public  final class LineReply extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:LineReply)
    LineReplyOrBuilder {
private static final long serialVersionUID = 0L;
  // Use LineReply.newBuilder() to construct.
  private LineReply(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private LineReply() {
    field1_ = java.util.Collections.emptyList();
    field4_ = "";
    field6_ = "";
    field8_ = "";
    field10_ = "";
    field12_ = "";
    field14_ = "";
    field16_ = "";
    field18_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new LineReply();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private LineReply(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              field1_ = new java.util.ArrayList<DistributionReply>();
              mutable_bitField0_ |= 0x00000001;
            }
            field1_.add(
                input.readMessage(DistributionReply.parser(), extensionRegistry));
            break;
          }
          case 16: {

            field2_ = input.readInt32();
            break;
          }
          case 26: {
            com.google.protobuf.Timestamp.Builder subBuilder = null;
            if (field3_ != null) {
              subBuilder = field3_.toBuilder();
            }
            field3_ = input.readMessage(com.google.protobuf.Timestamp.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(field3_);
              field3_ = subBuilder.buildPartial();
            }

            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            field4_ = s;
            break;
          }
          case 40: {

            field5_ = input.readInt32();
            break;
          }
          case 50: {
            java.lang.String s = input.readStringRequireUtf8();

            field6_ = s;
            break;
          }
          case 56: {

            field7_ = input.readInt32();
            break;
          }
          case 66: {
            java.lang.String s = input.readStringRequireUtf8();

            field8_ = s;
            break;
          }
          case 72: {

            field9_ = input.readInt32();
            break;
          }
          case 82: {
            java.lang.String s = input.readStringRequireUtf8();

            field10_ = s;
            break;
          }
          case 88: {

            field11_ = input.readInt32();
            break;
          }
          case 98: {
            java.lang.String s = input.readStringRequireUtf8();

            field12_ = s;
            break;
          }
          case 104: {

            field13_ = input.readInt32();
            break;
          }
          case 114: {
            java.lang.String s = input.readStringRequireUtf8();

            field14_ = s;
            break;
          }
          case 120: {

            field15_ = input.readInt32();
            break;
          }
          case 130: {
            java.lang.String s = input.readStringRequireUtf8();

            field16_ = s;
            break;
          }
          case 136: {

            field17_ = input.readInt32();
            break;
          }
          case 146: {
            java.lang.String s = input.readStringRequireUtf8();

            field18_ = s;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        field1_ = java.util.Collections.unmodifiableList(field1_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return Header.internal_static_com_remcarpediem_feignprotobuf_proto_dto_LineReply_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return Header.internal_static_com_remcarpediem_feignprotobuf_proto_dto_LineReply_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            LineReply.class, LineReply.Builder.class);
  }

  public static final int FIELD1_FIELD_NUMBER = 1;
  private java.util.List<DistributionReply> field1_;
  /**
   * <code>repeated .com.remcarpediem.feignprotobuf.proto.dto.DistributionReplyDTO field1 = 1;</code>
   */
  public java.util.List<DistributionReply> getField1List() {
    return field1_;
  }
  /**
   * <code>repeated .com.remcarpediem.feignprotobuf.proto.dto.DistributionReplyDTO field1 = 1;</code>
   */
  public java.util.List<? extends DistributionReplyOrBuilder>
      getField1OrBuilderList() {
    return field1_;
  }
  /**
   * <code>repeated .com.remcarpediem.feignprotobuf.proto.dto.DistributionReplyDTO field1 = 1;</code>
   */
  public int getField1Count() {
    return field1_.size();
  }
  /**
   * <code>repeated .com.remcarpediem.feignprotobuf.proto.dto.DistributionReplyDTO field1 = 1;</code>
   */
  public DistributionReply getField1(int index) {
    return field1_.get(index);
  }
  /**
   * <code>repeated .com.remcarpediem.feignprotobuf.proto.dto.DistributionReplyDTO field1 = 1;</code>
   */
  public DistributionReplyOrBuilder getField1OrBuilder(
      int index) {
    return field1_.get(index);
  }

  public static final int FIELD2_FIELD_NUMBER = 2;
  private int field2_;
  /**
   * <code>int32 field2 = 2;</code>
   */
  public int getField2() {
    return field2_;
  }

  public static final int FIELD3_FIELD_NUMBER = 3;
  private com.google.protobuf.Timestamp field3_;
  /**
   * <code>.google.protobuf.Timestamp field3 = 3;</code>
   */
  public boolean hasField3() {
    return field3_ != null;
  }
  /**
   * <code>.google.protobuf.Timestamp field3 = 3;</code>
   */
  public com.google.protobuf.Timestamp getField3() {
    return field3_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : field3_;
  }
  /**
   * <code>.google.protobuf.Timestamp field3 = 3;</code>
   */
  public com.google.protobuf.TimestampOrBuilder getField3OrBuilder() {
    return getField3();
  }

  public static final int FIELD4_FIELD_NUMBER = 4;
  private volatile java.lang.Object field4_;
  /**
   * <code>string field4 = 4;</code>
   */
  public java.lang.String getField4() {
    java.lang.Object ref = field4_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      field4_ = s;
      return s;
    }
  }
  /**
   * <code>string field4 = 4;</code>
   */
  public com.google.protobuf.ByteString
      getField4Bytes() {
    java.lang.Object ref = field4_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      field4_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int FIELD5_FIELD_NUMBER = 5;
  private int field5_;
  /**
   * <code>int32 field5 = 5;</code>
   */
  public int getField5() {
    return field5_;
  }

  public static final int FIELD6_FIELD_NUMBER = 6;
  private volatile java.lang.Object field6_;
  /**
   * <code>string field6 = 6;</code>
   */
  public java.lang.String getField6() {
    java.lang.Object ref = field6_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      field6_ = s;
      return s;
    }
  }
  /**
   * <code>string field6 = 6;</code>
   */
  public com.google.protobuf.ByteString
      getField6Bytes() {
    java.lang.Object ref = field6_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      field6_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int FIELD7_FIELD_NUMBER = 7;
  private int field7_;
  /**
   * <code>int32 field7 = 7;</code>
   */
  public int getField7() {
    return field7_;
  }

  public static final int FIELD8_FIELD_NUMBER = 8;
  private volatile java.lang.Object field8_;
  /**
   * <code>string field8 = 8;</code>
   */
  public java.lang.String getField8() {
    java.lang.Object ref = field8_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      field8_ = s;
      return s;
    }
  }
  /**
   * <code>string field8 = 8;</code>
   */
  public com.google.protobuf.ByteString
      getField8Bytes() {
    java.lang.Object ref = field8_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      field8_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int FIELD9_FIELD_NUMBER = 9;
  private int field9_;
  /**
   * <code>int32 field9 = 9;</code>
   */
  public int getField9() {
    return field9_;
  }

  public static final int FIELD10_FIELD_NUMBER = 10;
  private volatile java.lang.Object field10_;
  /**
   * <code>string field10 = 10;</code>
   */
  public java.lang.String getField10() {
    java.lang.Object ref = field10_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      field10_ = s;
      return s;
    }
  }
  /**
   * <code>string field10 = 10;</code>
   */
  public com.google.protobuf.ByteString
      getField10Bytes() {
    java.lang.Object ref = field10_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      field10_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int FIELD11_FIELD_NUMBER = 11;
  private int field11_;
  /**
   * <code>int32 field11 = 11;</code>
   */
  public int getField11() {
    return field11_;
  }

  public static final int FIELD12_FIELD_NUMBER = 12;
  private volatile java.lang.Object field12_;
  /**
   * <code>string field12 = 12;</code>
   */
  public java.lang.String getField12() {
    java.lang.Object ref = field12_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      field12_ = s;
      return s;
    }
  }
  /**
   * <code>string field12 = 12;</code>
   */
  public com.google.protobuf.ByteString
      getField12Bytes() {
    java.lang.Object ref = field12_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      field12_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int FIELD13_FIELD_NUMBER = 13;
  private int field13_;
  /**
   * <code>int32 field13 = 13;</code>
   */
  public int getField13() {
    return field13_;
  }

  public static final int FIELD14_FIELD_NUMBER = 14;
  private volatile java.lang.Object field14_;
  /**
   * <code>string field14 = 14;</code>
   */
  public java.lang.String getField14() {
    java.lang.Object ref = field14_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      field14_ = s;
      return s;
    }
  }
  /**
   * <code>string field14 = 14;</code>
   */
  public com.google.protobuf.ByteString
      getField14Bytes() {
    java.lang.Object ref = field14_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      field14_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int FIELD15_FIELD_NUMBER = 15;
  private int field15_;
  /**
   * <code>int32 field15 = 15;</code>
   */
  public int getField15() {
    return field15_;
  }

  public static final int FIELD16_FIELD_NUMBER = 16;
  private volatile java.lang.Object field16_;
  /**
   * <code>string field16 = 16;</code>
   */
  public java.lang.String getField16() {
    java.lang.Object ref = field16_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      field16_ = s;
      return s;
    }
  }
  /**
   * <code>string field16 = 16;</code>
   */
  public com.google.protobuf.ByteString
      getField16Bytes() {
    java.lang.Object ref = field16_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      field16_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int FIELD17_FIELD_NUMBER = 17;
  private int field17_;
  /**
   * <code>int32 field17 = 17;</code>
   */
  public int getField17() {
    return field17_;
  }

  public static final int FIELD18_FIELD_NUMBER = 18;
  private volatile java.lang.Object field18_;
  /**
   * <code>string field18 = 18;</code>
   */
  public java.lang.String getField18() {
    java.lang.Object ref = field18_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      field18_ = s;
      return s;
    }
  }
  /**
   * <code>string field18 = 18;</code>
   */
  public com.google.protobuf.ByteString
      getField18Bytes() {
    java.lang.Object ref = field18_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      field18_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < field1_.size(); i++) {
      output.writeMessage(1, field1_.get(i));
    }
    if (field2_ != 0) {
      output.writeInt32(2, field2_);
    }
    if (field3_ != null) {
      output.writeMessage(3, getField3());
    }
    if (!getField4Bytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, field4_);
    }
    if (field5_ != 0) {
      output.writeInt32(5, field5_);
    }
    if (!getField6Bytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, field6_);
    }
    if (field7_ != 0) {
      output.writeInt32(7, field7_);
    }
    if (!getField8Bytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 8, field8_);
    }
    if (field9_ != 0) {
      output.writeInt32(9, field9_);
    }
    if (!getField10Bytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 10, field10_);
    }
    if (field11_ != 0) {
      output.writeInt32(11, field11_);
    }
    if (!getField12Bytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 12, field12_);
    }
    if (field13_ != 0) {
      output.writeInt32(13, field13_);
    }
    if (!getField14Bytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 14, field14_);
    }
    if (field15_ != 0) {
      output.writeInt32(15, field15_);
    }
    if (!getField16Bytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 16, field16_);
    }
    if (field17_ != 0) {
      output.writeInt32(17, field17_);
    }
    if (!getField18Bytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 18, field18_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < field1_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, field1_.get(i));
    }
    if (field2_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, field2_);
    }
    if (field3_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getField3());
    }
    if (!getField4Bytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, field4_);
    }
    if (field5_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(5, field5_);
    }
    if (!getField6Bytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, field6_);
    }
    if (field7_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(7, field7_);
    }
    if (!getField8Bytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, field8_);
    }
    if (field9_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(9, field9_);
    }
    if (!getField10Bytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(10, field10_);
    }
    if (field11_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(11, field11_);
    }
    if (!getField12Bytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(12, field12_);
    }
    if (field13_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(13, field13_);
    }
    if (!getField14Bytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(14, field14_);
    }
    if (field15_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(15, field15_);
    }
    if (!getField16Bytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(16, field16_);
    }
    if (field17_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(17, field17_);
    }
    if (!getField18Bytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(18, field18_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof LineReply)) {
      return super.equals(obj);
    }
    LineReply other = (LineReply) obj;

    if (!getField1List()
        .equals(other.getField1List())) return false;
    if (getField2()
        != other.getField2()) return false;
    if (hasField3() != other.hasField3()) return false;
    if (hasField3()) {
      if (!getField3()
          .equals(other.getField3())) return false;
    }
    if (!getField4()
        .equals(other.getField4())) return false;
    if (getField5()
        != other.getField5()) return false;
    if (!getField6()
        .equals(other.getField6())) return false;
    if (getField7()
        != other.getField7()) return false;
    if (!getField8()
        .equals(other.getField8())) return false;
    if (getField9()
        != other.getField9()) return false;
    if (!getField10()
        .equals(other.getField10())) return false;
    if (getField11()
        != other.getField11()) return false;
    if (!getField12()
        .equals(other.getField12())) return false;
    if (getField13()
        != other.getField13()) return false;
    if (!getField14()
        .equals(other.getField14())) return false;
    if (getField15()
        != other.getField15()) return false;
    if (!getField16()
        .equals(other.getField16())) return false;
    if (getField17()
        != other.getField17()) return false;
    if (!getField18()
        .equals(other.getField18())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getField1Count() > 0) {
      hash = (37 * hash) + FIELD1_FIELD_NUMBER;
      hash = (53 * hash) + getField1List().hashCode();
    }
    hash = (37 * hash) + FIELD2_FIELD_NUMBER;
    hash = (53 * hash) + getField2();
    if (hasField3()) {
      hash = (37 * hash) + FIELD3_FIELD_NUMBER;
      hash = (53 * hash) + getField3().hashCode();
    }
    hash = (37 * hash) + FIELD4_FIELD_NUMBER;
    hash = (53 * hash) + getField4().hashCode();
    hash = (37 * hash) + FIELD5_FIELD_NUMBER;
    hash = (53 * hash) + getField5();
    hash = (37 * hash) + FIELD6_FIELD_NUMBER;
    hash = (53 * hash) + getField6().hashCode();
    hash = (37 * hash) + FIELD7_FIELD_NUMBER;
    hash = (53 * hash) + getField7();
    hash = (37 * hash) + FIELD8_FIELD_NUMBER;
    hash = (53 * hash) + getField8().hashCode();
    hash = (37 * hash) + FIELD9_FIELD_NUMBER;
    hash = (53 * hash) + getField9();
    hash = (37 * hash) + FIELD10_FIELD_NUMBER;
    hash = (53 * hash) + getField10().hashCode();
    hash = (37 * hash) + FIELD11_FIELD_NUMBER;
    hash = (53 * hash) + getField11();
    hash = (37 * hash) + FIELD12_FIELD_NUMBER;
    hash = (53 * hash) + getField12().hashCode();
    hash = (37 * hash) + FIELD13_FIELD_NUMBER;
    hash = (53 * hash) + getField13();
    hash = (37 * hash) + FIELD14_FIELD_NUMBER;
    hash = (53 * hash) + getField14().hashCode();
    hash = (37 * hash) + FIELD15_FIELD_NUMBER;
    hash = (53 * hash) + getField15();
    hash = (37 * hash) + FIELD16_FIELD_NUMBER;
    hash = (53 * hash) + getField16().hashCode();
    hash = (37 * hash) + FIELD17_FIELD_NUMBER;
    hash = (53 * hash) + getField17();
    hash = (37 * hash) + FIELD18_FIELD_NUMBER;
    hash = (53 * hash) + getField18().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static LineReply parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static LineReply parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static LineReply parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static LineReply parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static LineReply parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static LineReply parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static LineReply parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static LineReply parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static LineReply parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static LineReply parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static LineReply parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static LineReply parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(LineReply prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code LineReply}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:LineReply)
          LineReplyOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Header.internal_static_com_remcarpediem_feignprotobuf_proto_dto_LineReply_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Header.internal_static_com_remcarpediem_feignprotobuf_proto_dto_LineReply_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              LineReply.class, LineReply.Builder.class);
    }

    // Construct using LineReply.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getField1FieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (field1Builder_ == null) {
        field1_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        field1Builder_.clear();
      }
      field2_ = 0;

      if (field3Builder_ == null) {
        field3_ = null;
      } else {
        field3_ = null;
        field3Builder_ = null;
      }
      field4_ = "";

      field5_ = 0;

      field6_ = "";

      field7_ = 0;

      field8_ = "";

      field9_ = 0;

      field10_ = "";

      field11_ = 0;

      field12_ = "";

      field13_ = 0;

      field14_ = "";

      field15_ = 0;

      field16_ = "";

      field17_ = 0;

      field18_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return Header.internal_static_com_remcarpediem_feignprotobuf_proto_dto_LineReply_descriptor;
    }

    @java.lang.Override
    public LineReply getDefaultInstanceForType() {
      return LineReply.getDefaultInstance();
    }

    @java.lang.Override
    public LineReply build() {
      LineReply result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public LineReply buildPartial() {
      LineReply result = new LineReply(this);
      int from_bitField0_ = bitField0_;
      if (field1Builder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          field1_ = java.util.Collections.unmodifiableList(field1_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.field1_ = field1_;
      } else {
        result.field1_ = field1Builder_.build();
      }
      result.field2_ = field2_;
      if (field3Builder_ == null) {
        result.field3_ = field3_;
      } else {
        result.field3_ = field3Builder_.build();
      }
      result.field4_ = field4_;
      result.field5_ = field5_;
      result.field6_ = field6_;
      result.field7_ = field7_;
      result.field8_ = field8_;
      result.field9_ = field9_;
      result.field10_ = field10_;
      result.field11_ = field11_;
      result.field12_ = field12_;
      result.field13_ = field13_;
      result.field14_ = field14_;
      result.field15_ = field15_;
      result.field16_ = field16_;
      result.field17_ = field17_;
      result.field18_ = field18_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof LineReply) {
        return mergeFrom((LineReply)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(LineReply other) {
      if (other == LineReply.getDefaultInstance()) return this;
      if (field1Builder_ == null) {
        if (!other.field1_.isEmpty()) {
          if (field1_.isEmpty()) {
            field1_ = other.field1_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureField1IsMutable();
            field1_.addAll(other.field1_);
          }
          onChanged();
        }
      } else {
        if (!other.field1_.isEmpty()) {
          if (field1Builder_.isEmpty()) {
            field1Builder_.dispose();
            field1Builder_ = null;
            field1_ = other.field1_;
            bitField0_ = (bitField0_ & ~0x00000001);
            field1Builder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getField1FieldBuilder() : null;
          } else {
            field1Builder_.addAllMessages(other.field1_);
          }
        }
      }
      if (other.getField2() != 0) {
        setField2(other.getField2());
      }
      if (other.hasField3()) {
        mergeField3(other.getField3());
      }
      if (!other.getField4().isEmpty()) {
        field4_ = other.field4_;
        onChanged();
      }
      if (other.getField5() != 0) {
        setField5(other.getField5());
      }
      if (!other.getField6().isEmpty()) {
        field6_ = other.field6_;
        onChanged();
      }
      if (other.getField7() != 0) {
        setField7(other.getField7());
      }
      if (!other.getField8().isEmpty()) {
        field8_ = other.field8_;
        onChanged();
      }
      if (other.getField9() != 0) {
        setField9(other.getField9());
      }
      if (!other.getField10().isEmpty()) {
        field10_ = other.field10_;
        onChanged();
      }
      if (other.getField11() != 0) {
        setField11(other.getField11());
      }
      if (!other.getField12().isEmpty()) {
        field12_ = other.field12_;
        onChanged();
      }
      if (other.getField13() != 0) {
        setField13(other.getField13());
      }
      if (!other.getField14().isEmpty()) {
        field14_ = other.field14_;
        onChanged();
      }
      if (other.getField15() != 0) {
        setField15(other.getField15());
      }
      if (!other.getField16().isEmpty()) {
        field16_ = other.field16_;
        onChanged();
      }
      if (other.getField17() != 0) {
        setField17(other.getField17());
      }
      if (!other.getField18().isEmpty()) {
        field18_ = other.field18_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      LineReply parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (LineReply) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<DistributionReply> field1_ =
      java.util.Collections.emptyList();
    private void ensureField1IsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        field1_ = new java.util.ArrayList<DistributionReply>(field1_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
            DistributionReply, DistributionReply.Builder, DistributionReplyOrBuilder> field1Builder_;

    /**
     * <code>repeated .com.remcarpediem.feignprotobuf.proto.dto.DistributionReplyDTO field1 = 1;</code>
     */
    public java.util.List<DistributionReply> getField1List() {
      if (field1Builder_ == null) {
        return java.util.Collections.unmodifiableList(field1_);
      } else {
        return field1Builder_.getMessageList();
      }
    }
    /**
     * <code>repeated .com.remcarpediem.feignprotobuf.proto.dto.DistributionReplyDTO field1 = 1;</code>
     */
    public int getField1Count() {
      if (field1Builder_ == null) {
        return field1_.size();
      } else {
        return field1Builder_.getCount();
      }
    }
    /**
     * <code>repeated .com.remcarpediem.feignprotobuf.proto.dto.DistributionReplyDTO field1 = 1;</code>
     */
    public DistributionReply getField1(int index) {
      if (field1Builder_ == null) {
        return field1_.get(index);
      } else {
        return field1Builder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .com.remcarpediem.feignprotobuf.proto.dto.DistributionReplyDTO field1 = 1;</code>
     */
    public Builder setField1(
        int index, DistributionReply value) {
      if (field1Builder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureField1IsMutable();
        field1_.set(index, value);
        onChanged();
      } else {
        field1Builder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .com.remcarpediem.feignprotobuf.proto.dto.DistributionReplyDTO field1 = 1;</code>
     */
    public Builder setField1(
        int index, DistributionReply.Builder builderForValue) {
      if (field1Builder_ == null) {
        ensureField1IsMutable();
        field1_.set(index, builderForValue.build());
        onChanged();
      } else {
        field1Builder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.remcarpediem.feignprotobuf.proto.dto.DistributionReplyDTO field1 = 1;</code>
     */
    public Builder addField1(DistributionReply value) {
      if (field1Builder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureField1IsMutable();
        field1_.add(value);
        onChanged();
      } else {
        field1Builder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .com.remcarpediem.feignprotobuf.proto.dto.DistributionReplyDTO field1 = 1;</code>
     */
    public Builder addField1(
        int index, DistributionReply value) {
      if (field1Builder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureField1IsMutable();
        field1_.add(index, value);
        onChanged();
      } else {
        field1Builder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .com.remcarpediem.feignprotobuf.proto.dto.DistributionReplyDTO field1 = 1;</code>
     */
    public Builder addField1(
        DistributionReply.Builder builderForValue) {
      if (field1Builder_ == null) {
        ensureField1IsMutable();
        field1_.add(builderForValue.build());
        onChanged();
      } else {
        field1Builder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.remcarpediem.feignprotobuf.proto.dto.DistributionReplyDTO field1 = 1;</code>
     */
    public Builder addField1(
        int index, DistributionReply.Builder builderForValue) {
      if (field1Builder_ == null) {
        ensureField1IsMutable();
        field1_.add(index, builderForValue.build());
        onChanged();
      } else {
        field1Builder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.remcarpediem.feignprotobuf.proto.dto.DistributionReplyDTO field1 = 1;</code>
     */
    public Builder addAllField1(
        java.lang.Iterable<? extends DistributionReply> values) {
      if (field1Builder_ == null) {
        ensureField1IsMutable();
        addAll(
            values, field1_);
        onChanged();
      } else {
        field1Builder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .com.remcarpediem.feignprotobuf.proto.dto.DistributionReplyDTO field1 = 1;</code>
     */
    public Builder clearField1() {
      if (field1Builder_ == null) {
        field1_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        field1Builder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .com.remcarpediem.feignprotobuf.proto.dto.DistributionReplyDTO field1 = 1;</code>
     */
    public Builder removeField1(int index) {
      if (field1Builder_ == null) {
        ensureField1IsMutable();
        field1_.remove(index);
        onChanged();
      } else {
        field1Builder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .com.remcarpediem.feignprotobuf.proto.dto.DistributionReplyDTO field1 = 1;</code>
     */
    public DistributionReply.Builder getField1Builder(
        int index) {
      return getField1FieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .com.remcarpediem.feignprotobuf.proto.dto.DistributionReplyDTO field1 = 1;</code>
     */
    public DistributionReplyOrBuilder getField1OrBuilder(
        int index) {
      if (field1Builder_ == null) {
        return field1_.get(index);  } else {
        return field1Builder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .com.remcarpediem.feignprotobuf.proto.dto.DistributionReplyDTO field1 = 1;</code>
     */
    public java.util.List<? extends DistributionReplyOrBuilder>
         getField1OrBuilderList() {
      if (field1Builder_ != null) {
        return field1Builder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(field1_);
      }
    }
    /**
     * <code>repeated .com.remcarpediem.feignprotobuf.proto.dto.DistributionReplyDTO field1 = 1;</code>
     */
    public DistributionReply.Builder addField1Builder() {
      return getField1FieldBuilder().addBuilder(
          DistributionReply.getDefaultInstance());
    }
    /**
     * <code>repeated .com.remcarpediem.feignprotobuf.proto.dto.DistributionReplyDTO field1 = 1;</code>
     */
    public DistributionReply.Builder addField1Builder(
        int index) {
      return getField1FieldBuilder().addBuilder(
          index, DistributionReply.getDefaultInstance());
    }
    /**
     * <code>repeated .com.remcarpediem.feignprotobuf.proto.dto.DistributionReplyDTO field1 = 1;</code>
     */
    public java.util.List<DistributionReply.Builder>
         getField1BuilderList() {
      return getField1FieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
            DistributionReply, DistributionReply.Builder, DistributionReplyOrBuilder>
        getField1FieldBuilder() {
      if (field1Builder_ == null) {
        field1Builder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
                DistributionReply, DistributionReply.Builder, DistributionReplyOrBuilder>(
                field1_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        field1_ = null;
      }
      return field1Builder_;
    }

    private int field2_ ;
    /**
     * <code>int32 field2 = 2;</code>
     */
    public int getField2() {
      return field2_;
    }
    /**
     * <code>int32 field2 = 2;</code>
     */
    public Builder setField2(int value) {
      
      field2_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 field2 = 2;</code>
     */
    public Builder clearField2() {
      
      field2_ = 0;
      onChanged();
      return this;
    }

    private com.google.protobuf.Timestamp field3_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> field3Builder_;
    /**
     * <code>.google.protobuf.Timestamp field3 = 3;</code>
     */
    public boolean hasField3() {
      return field3Builder_ != null || field3_ != null;
    }
    /**
     * <code>.google.protobuf.Timestamp field3 = 3;</code>
     */
    public com.google.protobuf.Timestamp getField3() {
      if (field3Builder_ == null) {
        return field3_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : field3_;
      } else {
        return field3Builder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.Timestamp field3 = 3;</code>
     */
    public Builder setField3(com.google.protobuf.Timestamp value) {
      if (field3Builder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        field3_ = value;
        onChanged();
      } else {
        field3Builder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp field3 = 3;</code>
     */
    public Builder setField3(
        com.google.protobuf.Timestamp.Builder builderForValue) {
      if (field3Builder_ == null) {
        field3_ = builderForValue.build();
        onChanged();
      } else {
        field3Builder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp field3 = 3;</code>
     */
    public Builder mergeField3(com.google.protobuf.Timestamp value) {
      if (field3Builder_ == null) {
        if (field3_ != null) {
          field3_ =
            com.google.protobuf.Timestamp.newBuilder(field3_).mergeFrom(value).buildPartial();
        } else {
          field3_ = value;
        }
        onChanged();
      } else {
        field3Builder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp field3 = 3;</code>
     */
    public Builder clearField3() {
      if (field3Builder_ == null) {
        field3_ = null;
        onChanged();
      } else {
        field3_ = null;
        field3Builder_ = null;
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp field3 = 3;</code>
     */
    public com.google.protobuf.Timestamp.Builder getField3Builder() {
      
      onChanged();
      return getField3FieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.Timestamp field3 = 3;</code>
     */
    public com.google.protobuf.TimestampOrBuilder getField3OrBuilder() {
      if (field3Builder_ != null) {
        return field3Builder_.getMessageOrBuilder();
      } else {
        return field3_ == null ?
            com.google.protobuf.Timestamp.getDefaultInstance() : field3_;
      }
    }
    /**
     * <code>.google.protobuf.Timestamp field3 = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
        getField3FieldBuilder() {
      if (field3Builder_ == null) {
        field3Builder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                getField3(),
                getParentForChildren(),
                isClean());
        field3_ = null;
      }
      return field3Builder_;
    }

    private java.lang.Object field4_ = "";
    /**
     * <code>string field4 = 4;</code>
     */
    public java.lang.String getField4() {
      java.lang.Object ref = field4_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        field4_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string field4 = 4;</code>
     */
    public com.google.protobuf.ByteString
        getField4Bytes() {
      java.lang.Object ref = field4_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        field4_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string field4 = 4;</code>
     */
    public Builder setField4(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      field4_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string field4 = 4;</code>
     */
    public Builder clearField4() {
      
      field4_ = getDefaultInstance().getField4();
      onChanged();
      return this;
    }
    /**
     * <code>string field4 = 4;</code>
     */
    public Builder setField4Bytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      field4_ = value;
      onChanged();
      return this;
    }

    private int field5_ ;
    /**
     * <code>int32 field5 = 5;</code>
     */
    public int getField5() {
      return field5_;
    }
    /**
     * <code>int32 field5 = 5;</code>
     */
    public Builder setField5(int value) {
      
      field5_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 field5 = 5;</code>
     */
    public Builder clearField5() {
      
      field5_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object field6_ = "";
    /**
     * <code>string field6 = 6;</code>
     */
    public java.lang.String getField6() {
      java.lang.Object ref = field6_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        field6_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string field6 = 6;</code>
     */
    public com.google.protobuf.ByteString
        getField6Bytes() {
      java.lang.Object ref = field6_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        field6_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string field6 = 6;</code>
     */
    public Builder setField6(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      field6_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string field6 = 6;</code>
     */
    public Builder clearField6() {
      
      field6_ = getDefaultInstance().getField6();
      onChanged();
      return this;
    }
    /**
     * <code>string field6 = 6;</code>
     */
    public Builder setField6Bytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      field6_ = value;
      onChanged();
      return this;
    }

    private int field7_ ;
    /**
     * <code>int32 field7 = 7;</code>
     */
    public int getField7() {
      return field7_;
    }
    /**
     * <code>int32 field7 = 7;</code>
     */
    public Builder setField7(int value) {
      
      field7_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 field7 = 7;</code>
     */
    public Builder clearField7() {
      
      field7_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object field8_ = "";
    /**
     * <code>string field8 = 8;</code>
     */
    public java.lang.String getField8() {
      java.lang.Object ref = field8_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        field8_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string field8 = 8;</code>
     */
    public com.google.protobuf.ByteString
        getField8Bytes() {
      java.lang.Object ref = field8_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        field8_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string field8 = 8;</code>
     */
    public Builder setField8(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      field8_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string field8 = 8;</code>
     */
    public Builder clearField8() {
      
      field8_ = getDefaultInstance().getField8();
      onChanged();
      return this;
    }
    /**
     * <code>string field8 = 8;</code>
     */
    public Builder setField8Bytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      field8_ = value;
      onChanged();
      return this;
    }

    private int field9_ ;
    /**
     * <code>int32 field9 = 9;</code>
     */
    public int getField9() {
      return field9_;
    }
    /**
     * <code>int32 field9 = 9;</code>
     */
    public Builder setField9(int value) {
      
      field9_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 field9 = 9;</code>
     */
    public Builder clearField9() {
      
      field9_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object field10_ = "";
    /**
     * <code>string field10 = 10;</code>
     */
    public java.lang.String getField10() {
      java.lang.Object ref = field10_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        field10_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string field10 = 10;</code>
     */
    public com.google.protobuf.ByteString
        getField10Bytes() {
      java.lang.Object ref = field10_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        field10_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string field10 = 10;</code>
     */
    public Builder setField10(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      field10_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string field10 = 10;</code>
     */
    public Builder clearField10() {
      
      field10_ = getDefaultInstance().getField10();
      onChanged();
      return this;
    }
    /**
     * <code>string field10 = 10;</code>
     */
    public Builder setField10Bytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      field10_ = value;
      onChanged();
      return this;
    }

    private int field11_ ;
    /**
     * <code>int32 field11 = 11;</code>
     */
    public int getField11() {
      return field11_;
    }
    /**
     * <code>int32 field11 = 11;</code>
     */
    public Builder setField11(int value) {
      
      field11_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 field11 = 11;</code>
     */
    public Builder clearField11() {
      
      field11_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object field12_ = "";
    /**
     * <code>string field12 = 12;</code>
     */
    public java.lang.String getField12() {
      java.lang.Object ref = field12_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        field12_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string field12 = 12;</code>
     */
    public com.google.protobuf.ByteString
        getField12Bytes() {
      java.lang.Object ref = field12_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        field12_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string field12 = 12;</code>
     */
    public Builder setField12(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      field12_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string field12 = 12;</code>
     */
    public Builder clearField12() {
      
      field12_ = getDefaultInstance().getField12();
      onChanged();
      return this;
    }
    /**
     * <code>string field12 = 12;</code>
     */
    public Builder setField12Bytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      field12_ = value;
      onChanged();
      return this;
    }

    private int field13_ ;
    /**
     * <code>int32 field13 = 13;</code>
     */
    public int getField13() {
      return field13_;
    }
    /**
     * <code>int32 field13 = 13;</code>
     */
    public Builder setField13(int value) {
      
      field13_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 field13 = 13;</code>
     */
    public Builder clearField13() {
      
      field13_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object field14_ = "";
    /**
     * <code>string field14 = 14;</code>
     */
    public java.lang.String getField14() {
      java.lang.Object ref = field14_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        field14_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string field14 = 14;</code>
     */
    public com.google.protobuf.ByteString
        getField14Bytes() {
      java.lang.Object ref = field14_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        field14_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string field14 = 14;</code>
     */
    public Builder setField14(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      field14_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string field14 = 14;</code>
     */
    public Builder clearField14() {
      
      field14_ = getDefaultInstance().getField14();
      onChanged();
      return this;
    }
    /**
     * <code>string field14 = 14;</code>
     */
    public Builder setField14Bytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      field14_ = value;
      onChanged();
      return this;
    }

    private int field15_ ;
    /**
     * <code>int32 field15 = 15;</code>
     */
    public int getField15() {
      return field15_;
    }
    /**
     * <code>int32 field15 = 15;</code>
     */
    public Builder setField15(int value) {
      
      field15_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 field15 = 15;</code>
     */
    public Builder clearField15() {
      
      field15_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object field16_ = "";
    /**
     * <code>string field16 = 16;</code>
     */
    public java.lang.String getField16() {
      java.lang.Object ref = field16_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        field16_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string field16 = 16;</code>
     */
    public com.google.protobuf.ByteString
        getField16Bytes() {
      java.lang.Object ref = field16_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        field16_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string field16 = 16;</code>
     */
    public Builder setField16(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      field16_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string field16 = 16;</code>
     */
    public Builder clearField16() {
      
      field16_ = getDefaultInstance().getField16();
      onChanged();
      return this;
    }
    /**
     * <code>string field16 = 16;</code>
     */
    public Builder setField16Bytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      field16_ = value;
      onChanged();
      return this;
    }

    private int field17_ ;
    /**
     * <code>int32 field17 = 17;</code>
     */
    public int getField17() {
      return field17_;
    }
    /**
     * <code>int32 field17 = 17;</code>
     */
    public Builder setField17(int value) {
      
      field17_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 field17 = 17;</code>
     */
    public Builder clearField17() {
      
      field17_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object field18_ = "";
    /**
     * <code>string field18 = 18;</code>
     */
    public java.lang.String getField18() {
      java.lang.Object ref = field18_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        field18_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string field18 = 18;</code>
     */
    public com.google.protobuf.ByteString
        getField18Bytes() {
      java.lang.Object ref = field18_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        field18_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string field18 = 18;</code>
     */
    public Builder setField18(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      field18_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string field18 = 18;</code>
     */
    public Builder clearField18() {
      
      field18_ = getDefaultInstance().getField18();
      onChanged();
      return this;
    }
    /**
     * <code>string field18 = 18;</code>
     */
    public Builder setField18Bytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      field18_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:LineReply)
  }

  // @@protoc_insertion_point(class_scope:LineReply)
  private static final LineReply DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new LineReply();
  }

  public static LineReply getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<LineReply>
      PARSER = new com.google.protobuf.AbstractParser<LineReply>() {
    @java.lang.Override
    public LineReply parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new LineReply(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<LineReply> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<LineReply> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public LineReply getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

