// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user.proto

package com.remcarpediem.feignprotobuf.proto.dto;

public interface UserDTOOrBuilder extends
    // @@protoc_insertion_point(interface_extends:UserDTO)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 id = 1;</code>
   */
  int getId();

  /**
   * <code>string name = 2;</code>
   */
  java.lang.String getName();
  /**
   * <code>string name = 2;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string url = 3;</code>
   */
  java.lang.String getUrl();
  /**
   * <code>string url = 3;</code>
   */
  com.google.protobuf.ByteString
      getUrlBytes();
}
