server:
  port: 9093

#management.security.enabled: false
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8011/eureka/
  instance:
    prefer-ip-address: true
spring:
  application:
    name: user-common
