// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: header.proto

package com.remcarpediem.feignprotobuf.grpc.dto;

public interface DistributionReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.remcarpediem.feignprotobuf.grpc.dto.DistributionReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string field1 = 1;</code>
   */
  java.lang.String getField1();
  /**
   * <code>string field1 = 1;</code>
   */
  com.google.protobuf.ByteString
      getField1Bytes();

  /**
   * <code>int32 field2 = 2;</code>
   */
  int getField2();

  /**
   * <code>.google.protobuf.Timestamp field3 = 3;</code>
   */
  boolean hasField3();
  /**
   * <code>.google.protobuf.Timestamp field3 = 3;</code>
   */
  com.google.protobuf.Timestamp getField3();
  /**
   * <code>.google.protobuf.Timestamp field3 = 3;</code>
   */
  com.google.protobuf.TimestampOrBuilder getField3OrBuilder();

  /**
   * <code>string field4 = 4;</code>
   */
  java.lang.String getField4();
  /**
   * <code>string field4 = 4;</code>
   */
  com.google.protobuf.ByteString
      getField4Bytes();

  /**
   * <code>int32 field5 = 5;</code>
   */
  int getField5();

  /**
   * <code>string field6 = 6;</code>
   */
  java.lang.String getField6();
  /**
   * <code>string field6 = 6;</code>
   */
  com.google.protobuf.ByteString
      getField6Bytes();

  /**
   * <code>int32 field7 = 7;</code>
   */
  int getField7();

  /**
   * <code>string field8 = 8;</code>
   */
  java.lang.String getField8();
  /**
   * <code>string field8 = 8;</code>
   */
  com.google.protobuf.ByteString
      getField8Bytes();

  /**
   * <code>int32 field9 = 9;</code>
   */
  int getField9();

  /**
   * <code>string field10 = 10;</code>
   */
  java.lang.String getField10();
  /**
   * <code>string field10 = 10;</code>
   */
  com.google.protobuf.ByteString
      getField10Bytes();

  /**
   * <code>int32 field11 = 11;</code>
   */
  int getField11();

  /**
   * <code>string field12 = 12;</code>
   */
  java.lang.String getField12();
  /**
   * <code>string field12 = 12;</code>
   */
  com.google.protobuf.ByteString
      getField12Bytes();

  /**
   * <code>int32 field13 = 13;</code>
   */
  int getField13();

  /**
   * <code>string field14 = 14;</code>
   */
  java.lang.String getField14();
  /**
   * <code>string field14 = 14;</code>
   */
  com.google.protobuf.ByteString
      getField14Bytes();

  /**
   * <code>int32 field15 = 15;</code>
   */
  int getField15();

  /**
   * <code>string field16 = 16;</code>
   */
  java.lang.String getField16();
  /**
   * <code>string field16 = 16;</code>
   */
  com.google.protobuf.ByteString
      getField16Bytes();

  /**
   * <code>int32 field17 = 17;</code>
   */
  int getField17();

  /**
   * <code>string field18 = 18;</code>
   */
  java.lang.String getField18();
  /**
   * <code>string field18 = 18;</code>
   */
  com.google.protobuf.ByteString
      getField18Bytes();
}
