// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: header.proto

package com.remcarpediem.feignprotobuf.grpc.dto;

public final class HeaderOuterClass {
  private HeaderOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_remcarpediem_feignprotobuf_grpc_dto_HeaderRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_remcarpediem_feignprotobuf_grpc_dto_HeaderRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_remcarpediem_feignprotobuf_grpc_dto_HeaderReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_remcarpediem_feignprotobuf_grpc_dto_HeaderReply_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_remcarpediem_feignprotobuf_grpc_dto_LineReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_remcarpediem_feignprotobuf_grpc_dto_LineReply_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_remcarpediem_feignprotobuf_grpc_dto_DistributionReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_remcarpediem_feignprotobuf_grpc_dto_DistributionReply_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014header.proto\022\'com.remcarpediem.feignpr" +
      "otobuf.grpc.dto\032\037google/protobuf/timesta" +
      "mp.proto\"\035\n\rHeaderRequest\022\014\n\004name\030\001 \001(\t\"" +
      "\206\003\n\013HeaderReply\022B\n\006field1\030\001 \003(\01322.com.re" +
      "mcarpediem.feignprotobuf.grpc.dto.LineRe" +
      "ply\022\016\n\006field2\030\002 \001(\005\022*\n\006field3\030\003 \001(\0132\032.go" +
      "ogle.protobuf.Timestamp\022\016\n\006field4\030\004 \001(\t\022" +
      "\016\n\006field5\030\005 \001(\005\022\016\n\006field6\030\006 \001(\t\022\016\n\006field" +
      "7\030\007 \001(\005\022\016\n\006field8\030\010 \001(\t\022\016\n\006field9\030\t \001(\005\022" +
      "\017\n\007field10\030\n \001(\t\022\017\n\007field11\030\013 \001(\005\022\017\n\007fie" +
      "ld12\030\014 \001(\t\022\017\n\007field13\030\r \001(\005\022\017\n\007field14\030\016" +
      " \001(\t\022\017\n\007field15\030\017 \001(\005\022\017\n\007field16\030\020 \001(\t\022\017" +
      "\n\007field17\030\021 \001(\005\022\017\n\007field18\030\022 \001(\t\"\214\003\n\tLin" +
      "eReply\022J\n\006field1\030\001 \003(\0132:.com.remcarpedie" +
      "m.feignprotobuf.grpc.dto.DistributionRep" +
      "ly\022\016\n\006field2\030\002 \001(\005\022*\n\006field3\030\003 \001(\0132\032.goo" +
      "gle.protobuf.Timestamp\022\016\n\006field4\030\004 \001(\t\022\016" +
      "\n\006field5\030\005 \001(\005\022\016\n\006field6\030\006 \001(\t\022\016\n\006field7" +
      "\030\007 \001(\005\022\016\n\006field8\030\010 \001(\t\022\016\n\006field9\030\t \001(\005\022\017" +
      "\n\007field10\030\n \001(\t\022\017\n\007field11\030\013 \001(\005\022\017\n\007fiel" +
      "d12\030\014 \001(\t\022\017\n\007field13\030\r \001(\005\022\017\n\007field14\030\016 " +
      "\001(\t\022\017\n\007field15\030\017 \001(\005\022\017\n\007field16\030\020 \001(\t\022\017\n" +
      "\007field17\030\021 \001(\005\022\017\n\007field18\030\022 \001(\t\"\330\002\n\021Dist" +
      "ributionReply\022\016\n\006field1\030\001 \001(\t\022\016\n\006field2\030" +
      "\002 \001(\005\022*\n\006field3\030\003 \001(\0132\032.google.protobuf." +
      "Timestamp\022\016\n\006field4\030\004 \001(\t\022\016\n\006field5\030\005 \001(" +
      "\005\022\016\n\006field6\030\006 \001(\t\022\016\n\006field7\030\007 \001(\005\022\016\n\006fie" +
      "ld8\030\010 \001(\t\022\016\n\006field9\030\t \001(\005\022\017\n\007field10\030\n \001" +
      "(\t\022\017\n\007field11\030\013 \001(\005\022\017\n\007field12\030\014 \001(\t\022\017\n\007" +
      "field13\030\r \001(\005\022\017\n\007field14\030\016 \001(\t\022\017\n\007field1" +
      "5\030\017 \001(\005\022\017\n\007field16\030\020 \001(\t\022\017\n\007field17\030\021 \001(" +
      "\005\022\017\n\007field18\030\022 \001(\t2\213\001\n\006Header\022\200\001\n\016reques" +
      "tMessage\0226.com.remcarpediem.feignprotobu" +
      "f.grpc.dto.HeaderRequest\0324.com.remcarped" +
      "iem.feignprotobuf.grpc.dto.HeaderReply\"\000" +
      "B+\n\'com.remcarpediem.feignprotobuf.grpc." +
      "dtoP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.TimestampProto.getDescriptor(),
        }, assigner);
    internal_static_com_remcarpediem_feignprotobuf_grpc_dto_HeaderRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_remcarpediem_feignprotobuf_grpc_dto_HeaderRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_remcarpediem_feignprotobuf_grpc_dto_HeaderRequest_descriptor,
        new java.lang.String[] { "Name", });
    internal_static_com_remcarpediem_feignprotobuf_grpc_dto_HeaderReply_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_remcarpediem_feignprotobuf_grpc_dto_HeaderReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_remcarpediem_feignprotobuf_grpc_dto_HeaderReply_descriptor,
        new java.lang.String[] { "Field1", "Field2", "Field3", "Field4", "Field5", "Field6", "Field7", "Field8", "Field9", "Field10", "Field11", "Field12", "Field13", "Field14", "Field15", "Field16", "Field17", "Field18", });
    internal_static_com_remcarpediem_feignprotobuf_grpc_dto_LineReply_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_remcarpediem_feignprotobuf_grpc_dto_LineReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_remcarpediem_feignprotobuf_grpc_dto_LineReply_descriptor,
        new java.lang.String[] { "Field1", "Field2", "Field3", "Field4", "Field5", "Field6", "Field7", "Field8", "Field9", "Field10", "Field11", "Field12", "Field13", "Field14", "Field15", "Field16", "Field17", "Field18", });
    internal_static_com_remcarpediem_feignprotobuf_grpc_dto_DistributionReply_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_com_remcarpediem_feignprotobuf_grpc_dto_DistributionReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_remcarpediem_feignprotobuf_grpc_dto_DistributionReply_descriptor,
        new java.lang.String[] { "Field1", "Field2", "Field3", "Field4", "Field5", "Field6", "Field7", "Field8", "Field9", "Field10", "Field11", "Field12", "Field13", "Field14", "Field15", "Field16", "Field17", "Field18", });
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
