// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: header.proto

package com.remcarpediem.feignprotobuf.grpc.dto;

public interface HeaderRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.remcarpediem.feignprotobuf.grpc.dto.HeaderRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();
}
